name: build et deploiement site aws
on: [push, workflow_dispatch]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: date
          run: date

        - name: install python3.11
          uses: actions/setup-python@v5
          with:
            python-version: '3.11'

        - name: install mkdocs
          run: pip install mkdocs

        - name: ls
          run: ls

        - name: build test
          run: mkdocs build

        - name: ls
          run: ls

        - name: artifact upload
          uses: actions/upload-artifact@v4
          with:
            name: site
            path: site/

    deploiement:
        runs-on: self-hosted
        steps:
        - name: artifact download
          uses: actions/download-artifact@v4
          with: 
            name: site

        - name: ls
          run: ls
  
        - name: deploiement
          run: aws s3 sync site/ s3://benjaminmelki-test/

        - name: site adresse
          run: echo site http://benjaminmelki-test.s3-website.eu-west-3.amazonaws.com
        needs: build
